[tool.poetry]
name = "realtor"
version = "0.1.0"
description = ""
authors = ["Sanghun Jo <salr921@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "~3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
