# Generated by Django 3.2.18 on 2023-03-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.IntegerField(choices=[(1, "Submitted"), (2, "Checking"), (3, "Accepted")])),
                ("comment", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PreferredProperty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city", models.CharField(max_length=5)),
                ("district", models.CharField(max_length=3)),
                ("zone", models.CharField(max_length=3)),
                ("property_type", models.IntegerField(choices=[(1, "Purchase"), (2, "Longterm"), (3, "Monthly")])),
                (
                    "detailed_type",
                    models.IntegerField(
                        choices=[(1, "One Room"), (2, "Two Room"), (3, "Officetel"), (4, "Apartment")]
                    ),
                ),
                ("budget_from", models.IntegerField()),
                ("budget_to", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Agent",
        ),
    ]
