# Generated by Django 3.2.18 on 2023-05-22 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preferredproperty",
            name="users",
        ),
        migrations.AddField(
            model_name="preferredproperty",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="agent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="users.agent"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
