# Generated by Django 3.2.18 on 2023-04-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="agents",
            field=models.ManyToManyField(to="transactions.Agent"),
        ),
    ]
