# Generated by Django 3.2.18 on 2023-03-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="detailed_type",
            field=models.IntegerField(
                choices=[
                    (1, "One Room"),
                    (2, "Two Room"),
                    (3, "Officetel"),
                    (4, "Apartment"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.IntegerField(
                choices=[(1, "Purchase"), (2, "Longterm"), (3, "Monthly")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Available"), (2, "In Progress"), (3, "Done")], default=1
            ),
        ),
    ]
