# Generated by Django 3.2.18 on 2023-03-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_auto_20230326_0753"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="detailed_type",
            field=models.IntegerField(
                choices=[
                    (1, "One Room"),
                    (2, "Two Room"),
                    (3, "Officetel"),
                    (4, "Apartment"),
                ],
                default=4,
            ),
        ),
    ]
