# Generated by Django 3.2.18 on 2023-04-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mortgage_ratio", models.DecimalField(decimal_places=2, max_digits=4)),
                ("down_payment", models.IntegerField()),
                ("agreements", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="transactions.agent")),
            ],
        ),
    ]
